export const SD_TAG_CATEGORIES = [
  "quality",
  "person-count",
  "person-relations",
  "character-name",
  "series-name",
  "camera",
  "character",
  "outfit",
  "pose",
  "background",
  "face",
  "effect",
] as const;

export type SdTagCategory = (typeof SD_TAG_CATEGORIES)[number];

type SdTagAttribute = Readonly<{
  category: SdTagCategory;
}>;

export const SD_TAG_ATTRIBUTES: Readonly<Record<string, SdTagAttribute>> = {
  "masterpiece": { category: "quality" },
  "best quality": { category: "quality" },
  "1girl": { category: "person-count" },
  "2girls": { category: "person-count" },
  "1boy": { category: "person-count" },
  "multiple girls": { category: "person-count" },
  "multiple boys": { category: "person-count" },
  "solo": { category: "person-relations" },
  "solo focus": { category: "person-relations" },
  "yuri": { category: "person-relations" },
  "hetero": { category: "person-relations" },
  "harem": { category: "person-relations" },
  "pov": { category: "camera" },
  "from behind": { category: "camera" },
  "from side": { category: "camera" },
  "from below": { category: "camera" },
  "from above": { category: "camera" },
  "dutch angle": { category: "camera" },
  "ass focus": { category: "camera" },
  "armpit focus": { category: "camera" },
  "breast focus": { category: "camera" },
  "portrait": { category: "camera" },
  "upper body": { category: "camera" },
  "cowboy shot": { category: "camera" },
  "full body": { category: "camera" },
  "straight-on": { category: "camera" },
  "three quarter view": { category: "camera" },
  "flat chest": { category: "character" },
  "small breasts": { category: "character" },
  "medium breasts": { category: "character" },
  "large breasts": { category: "character" },
  "huge breasts": { category: "character" },
  "red eyes": { category: "character" },
  "green eyes": { category: "character" },
  "blue eyes": { category: "character" },
  "black eyes": { category: "character" },
  "brown eyes": { category: "character" },
  "purple eyes": { category: "character" },
  "aqua eyes": { category: "character" },
  "orange eyes": { category: "character" },
  "grey eyes": { category: "character" },
  "pink eyes": { category: "character" },
  "yellow eyes": { category: "character" },
  "multicolored eyes": { category: "character" },
  "tareme": { category: "character" },
  "tsurime": { category: "character" },
  "eyelashes": { category: "character" },
  "blonde hair": { category: "character" },
  "red hair": { category: "character" },
  "green hair": { category: "character" },
  "blue hair": { category: "character" },
  "light blue hair": { category: "character" },
  "black hair": { category: "character" },
  "brown hair": { category: "character" },
  "light brown hair": { category: "character" },
  "purple hair": { category: "character" },
  "aqua hair": { category: "character" },
  "orange hair": { category: "character" },
  "grey hair": { category: "character" },
  "pink hair": { category: "character" },
  "white hair": { category: "character" },
  "gradient hair": { category: "character" },
  "multicolored hair": { category: "character" },
  "short hair": { category: "character" },
  "medium hair": { category: "character" },
  "long hair": { category: "character" },
  "straight hair": { category: "character" },
  "wavy hair": { category: "character" },
  "curly hair": { category: "character" },
  "messy hair": { category: "character" },
  "bob cut": { category: "character" },
  "ponytail": { category: "character" },
  "high ponytail": { category: "character" },
  "side ponytail": { category: "character" },
  "one side up": { category: "character" },
  "hair intakes": { category: "character" },
  "antenna hair": { category: "character" },
  "ahoge": { category: "character" },
  "twintails": { category: "character" },
  "low twintails": { category: "character" },
  "short twintails": { category: "character" },
  "blunt bangs": { category: "character" },
  "crossed bangs": { category: "character" },
  "parted bangs": { category: "character" },
  "curtained hair": { category: "character" },
  "asymmetrical bangs": { category: "character" },
  "hair over one eye": { category: "character" },
  "hair between eyes": { category: "character" },
  "sidelocks": { category: "character" },
  "braid": { category: "character" },
  "side braid": { category: "character" },
  "single braid": { category: "character" },
  "braided ponytail": { category: "character" },
  "hair bun": { category: "character" },
  "single bun": { category: "character" },
  "double bun": { category: "character" },
  "dark-skinned female": { category: "character" },
  "elf": { category: "character" },
  "pointy ears": { category: "character" },
  "dog girl": { category: "character" },
  "dog ears": { category: "character" },
  "dog tail": { category: "character" },
  "cat girl": { category: "character" },
  "cat ears": { category: "character" },
  "cat tail": { category: "character" },
  "fox girl": { category: "character" },
  "fox ears": { category: "character" },
  "fox tail": { category: "character" },
  "collarbone": { category: "outfit" },
  "skindentation": { category: "outfit" },
  "race queen": { category: "outfit" },
  "china dress": { category: "outfit" },
  "magical girl": { category: "outfit" },
  "bridal veil": { category: "outfit" },
  "wedding dress": { category: "outfit" },
  "school swimsuit": { category: "outfit" },
  "policewoman": { category: "outfit" },
  "cheerleader": { category: "outfit" },
  "gym uniform": { category: "outfit" },
  "santa costume": { category: "outfit" },
  "gym shirt": { category: "outfit" },
  "harem outfit": { category: "outfit" },
  "one-piece swimsuit": { category: "outfit" },
  "alternate costume": { category: "outfit" },
  "contemporary": { category: "outfit" },
  "casual": { category: "outfit" },
  "necktie": { category: "outfit" },
  "ribbed sweater": { category: "outfit" },
  "red brooch": { category: "outfit" },
  "bikini": { category: "outfit" },
  "ruffle bikini": { category: "outfit" },
  "plaid bikini": { category: "outfit" },
  "frilled bikini": { category: "outfit" },
  "micro bikini": { category: "outfit" },
  "o-ring bikini": { category: "outfit" },
  "cow print bikini": { category: "outfit" },
  "white bikini": { category: "outfit" },
  "black bikini": { category: "outfit" },
  "red bikini": { category: "outfit" },
  "green bikini": { category: "outfit" },
  "blue bikini": { category: "outfit" },
  "pink bikini": { category: "outfit" },
  "orange bikini": { category: "outfit" },
  "purple bikini": { category: "outfit" },
  "camisole": { category: "outfit" },
  "white camisole": { category: "outfit" },
  "black camisole": { category: "outfit" },
  "red camisole": { category: "outfit" },
  "green camisole": { category: "outfit" },
  "blue camisole": { category: "outfit" },
  "pink camisole": { category: "outfit" },
  "orange camisole": { category: "outfit" },
  "purple camisole": { category: "outfit" },
  "white bodysuit": { category: "outfit" },
  "black bodysuit": { category: "outfit" },
  "red bodysuit": { category: "outfit" },
  "green bodysuit": { category: "outfit" },
  "blue bodysuit": { category: "outfit" },
  "pink bodysuit": { category: "outfit" },
  "orange bodysuit": { category: "outfit" },
  "purple bodysuit": { category: "outfit" },
  "white jacket": { category: "outfit" },
  "black jacket": { category: "outfit" },
  "red jacket": { category: "outfit" },
  "green jacket": { category: "outfit" },
  "blue jacket": { category: "outfit" },
  "pink jacket": { category: "outfit" },
  "orange jacket": { category: "outfit" },
  "purple jacket": { category: "outfit" },
  "maid": { category: "outfit" },
  "maid bikini": { category: "outfit" },
  "shirt": { category: "outfit" },
  "white shirt": { category: "outfit" },
  "black shirt": { category: "outfit" },
  "red shirt": { category: "outfit" },
  "green shirt": { category: "outfit" },
  "blue shirt": { category: "outfit" },
  "pink shirt": { category: "outfit" },
  "orange shirt": { category: "outfit" },
  "purple shirt": { category: "outfit" },
  "dress": { category: "outfit" },
  "white dress": { category: "outfit" },
  "black dress": { category: "outfit" },
  "red dress": { category: "outfit" },
  "green dress": { category: "outfit" },
  "blue dress": { category: "outfit" },
  "pink dress": { category: "outfit" },
  "orange dress": { category: "outfit" },
  "purple dress": { category: "outfit" },
  "grey dress": { category: "outfit" },
  "dress shirt": { category: "outfit" },
  "skirt": { category: "outfit" },
  "white skirt": { category: "outfit" },
  "black skirt": { category: "outfit" },
  "red skirt": { category: "outfit" },
  "green skirt": { category: "outfit" },
  "blue skirt": { category: "outfit" },
  "pink skirt": { category: "outfit" },
  "orange skirt": { category: "outfit" },
  "purple skirt": { category: "outfit" },
  "miniskirt": { category: "outfit" },
  "pleated skirt": { category: "outfit" },
  "plaid skirt": { category: "outfit" },
  "bare arms": { category: "outfit" },
  "bare legs": { category: "outfit" },
  "sleeveless": { category: "outfit" },
  "sleeveless shirt": { category: "outfit" },
  "sleeveless dress": { category: "outfit" },
  "thighhighs": { category: "outfit" },
  "black thighhighs": { category: "outfit" },
  "white thighhighs": { category: "outfit" },
  "pantyhose": { category: "outfit" },
  "black pantyhose": { category: "outfit" },
  "school uniform": { category: "outfit" },
  "blazer": { category: "outfit" },
  "bowtie": { category: "outfit" },
  "neck ribbon": { category: "outfit" },
  "looking at viewer": { category: "pose" },
  "looking at another": { category: "pose" },
  "looking back": { category: "pose" },
  "standing": { category: "pose" },
  "sitting": { category: "pose" },
  "lying": { category: "pose" },
  "on back": { category: "pose" },
  "on stomach": { category: "pose" },
  "head tilt": { category: "pose" },
  "wariza": { category: "pose" },
  "hand up": { category: "pose" },
  "hands up": { category: "pose" },
  "heart hands": { category: "pose" },
  "indoors": { category: "background" },
  "outdoors": { category: "background" },
  "dark background": { category: "background" },
  "simple background": { category: "background" },
  "zoom layer": { category: "background" },
  "outline": { category: "background" },
  "bed": { category: "background" },
  "bed sheet": { category: "background" },
  "lamp": { category: "background" },
  "ocean": { category: "background" },
  "beach": { category: "background" },
  "rock": { category: "background" },
  "lens flare": { category: "background" },
  "classroom": { category: "background" },
  "school chair": { category: "background" },
  "window": { category: "background" },
  "blush": { category: "face" },
  "full-face blush": { category: "face" },
  "nose blush": { category: "face" },
  "smile": { category: "face" },
  "embarrassed": { category: "face" },
  "averting eyes": { category: "face" },
  "tears": { category: "face" },
  "open mouth": { category: "face" },
  "closed mouth": { category: "face" },
  "half-closed eyes": { category: "face" },
  "closed eyes": { category: "face" },
  "tongue": { category: "face" },
  "chestnut mouth": { category: "face" },
  "saliva": { category: "face" },
  "depth of field": { category: "effect" },
  "motion lines": { category: "effect" },
  "motion blur": { category: "effect" },
  "twitching": { category: "effect" },
  "trembling": { category: "effect" },
  "sound effects": { category: "effect" },
  "blurry background": { category: "effect" },
  "steam": { category: "effect" },
  "steaming body": { category: "effect" },
  "sweat": { category: "effect" },
  "very sweat": { category: "effect" },
  "shiny skin": { category: "effect" },
  "heart": { category: "effect" },
  "spoken heart": { category: "effect" },
};
